import type { Metadata } from "next";
import "./globals.css";
import { AxiosProvider } from "@/src/context/AxiosContext";
import { Toaster } from "@/src/components/ui/sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col font-sans">
        <AxiosProvider>{children}</AxiosProvider>
        <Toaster/>
      </body>
    </html>
  );
}
